/* ============================================================
   ABANDONED, BUT NOT FORGOTTEN — Mission Data
   All dates and figures are drawn from NASA/JPL mission records
   and NASA Science pages. Where a section is explicitly marked
   "creative interpretation," it is storytelling, not fact.
   ============================================================ */

const MISSIONS = [
  {
    id: "spirit",
    name: "Spirit",
    subtitle: "Mars Exploration Rover \u2013 A (MER-A)",
    location: "mars",
    locationLabel: "Mars \u2014 Gusev Crater",
    era: "2000s",
    status: "silent",
    statusLabel: "Silent",
    type: "Rover",
    launch: "June 10, 2003",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "January 3, 2004 (local landing date; January 4 UTC)",
    plannedDuration: "90 sols (about 92 Earth days)",
    actualDuration: "2,208 sols on the surface \u2014 more than 6 years",
    powerSource: "Solar panels charging rechargeable batteries",
    distance: "7.73 km (4.8 mi) driven",
    lastComm: "March 22, 2010",
    missionEnd: "May 25, 2011 \u2014 NASA ended efforts to make contact",
    shortStory: "Spirit was built to last 90 days. It kept exploring Mars for more than six years.",
    builtFor: "Spirit and its twin, Opportunity, were sent to Mars to act as robot geologists. Their job was to study rocks and soil for clues about whether the Martian climate was ever wet enough, and warm enough, to support life. Spirit carried cameras, a rock-grinding tool, and spectrometers that could read the chemistry of Martian rock without ever bringing a sample home.",
    journey: [
      { stage: "Launch", text: "Spirit lifted off from Cape Canaveral on June 10, 2003, atop a Delta II rocket." },
      { stage: "Cruise", text: "The spacecraft spent nearly seven months crossing space toward Mars." },
      { stage: "Landing", text: "Spirit touched down inside Gusev Crater on January 3, 2004 local time (January 4 UTC), in a basin scientists suspected was once a lake." },
      { stage: "First discoveries", text: "Within its first months, Spirit found volcanic rocks and mineral clues pointing to a wetter Martian past." },
      { stage: "Extended mission", text: "Long after its 90-sol warranty expired, Spirit kept climbing the Columbia Hills, uncovering silica deposits that hinted at ancient hot springs." },
      { stage: "Final signal", text: "In 2009 Spirit's wheels broke through a crust of soil and became trapped in soft sand. Its last transmission reached Earth on March 22, 2010." }
    ],
    discoveries: [
      { title: "Ancient water activity", text: "Spirit found mineral deposits, including sulfates, that only form in the presence of water \u2014 evidence Gusev Crater was once wetter than today." },
      { title: "Silica-rich soil", text: "Disturbed by its own dragging wheel, Spirit uncovered patches of nearly pure silica, a mineral signature associated on Earth with hot springs or steam vents." },
      { title: "A volcanic plain", text: "Spirit's landing site turned out to be covered in volcanic rock rather than lakebed sediment, reshaping scientists' picture of Gusev's history." }
    ],
    whyStopped: "Spirit became stuck in soft, sandy soil in 2009 while trying to cross a patch of ground that looked stable but wasn't. Engineers on Earth spent months attempting to free it. With the rover tilted at an angle that kept its solar panels from catching enough winter sunlight, its batteries eventually ran too low to power its survival heaters. Spirit fell silent during the Martian winter, and NASA formally ended the mission on May 25, 2011.",
    whereNow: "Spirit remains exactly where it stopped, embedded in the soil of the Columbia Hills inside Gusev Crater. No spacecraft has been sent to move it.",
    whatRemainsItems: ["Rover body and six wheels", "Cameras and science instruments", "Solar panels and robotic arm"],
    whatRemains: "The rover's frame, wheels, and instruments are still there, weathered by dust and temperature swings. Its true legacy is the data: years of images, spectra, and soil analysis that scientists still study today.",
    remainsCaption: "Spirit stopped communicating, but its hardware remains on Mars.",
    whyMatters: "The rover stopped moving. The science did not.",
    quote: "I was built for 90 sols. I stayed for years. I climbed hills I was never promised, and found traces of water in ground that looked completely dry.",
    sources: [{ label: "NASA Science \u2014 Spirit mission overview", url: "https://science.nasa.gov/mission/mer-spirit/" }, { label: "NASA/JPL \u2014 Mars Exploration Rovers", url: "https://mars.nasa.gov/mer/" }]
  },
  {
    id: "opportunity",
    name: "Opportunity",
    subtitle: "Mars Exploration Rover \u2013 B (MER-B)",
    location: "mars",
    locationLabel: "Mars \u2014 Perseverance Valley, Meridiani Planum",
    era: "2000s",
    status: "silent",
    statusLabel: "Silent",
    type: "Rover",
    launch: "July 7, 2003",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "January 25, 2004 UTC (January 24 local time at landing)",
    plannedDuration: "90 sols (about 92 Earth days)",
    actualDuration: "About 14 years and 5 months of surface operations \u2014 nearly 15 years",
    powerSource: "Solar panels charging rechargeable batteries",
    distance: "45.16 km (28.06 mi) driven \u2014 the longest distance any vehicle has traveled off Earth",
    lastComm: "June 10, 2018",
    missionEnd: "February 13, 2019 \u2014 NASA declared the mission complete",
    shortStory: "Opportunity was designed to drive about a kilometer. It ended up crossing a marathon's worth of Mars.",
    builtFor: "Opportunity was Spirit's twin, landing on the opposite side of Mars to search for the same thing: signs that liquid water once shaped the planet's surface. Its cameras, microscope, and rock-abrasion tool let scientists read the layered history preserved in Martian bedrock.",
    journey: [
      { stage: "Launch", text: "Opportunity launched from Cape Canaveral on July 7, 2003, three weeks after Spirit." },
      { stage: "Cruise", text: "The spacecraft traveled roughly seven months to reach the Meridiani Planum region of Mars." },
      { stage: "Landing", text: "Opportunity landed on January 25, 2004, rolling to a stop inside a small crater \u2014 a rare stroke of luck that put bedrock right in view of its cameras." },
      { stage: "First discoveries", text: "Within weeks, Opportunity found small spherical mineral grains nicknamed 'blueberries,' later confirmed to be hematite that forms in water." },
      { stage: "Extended mission", text: "Opportunity spent years exploring craters along Meridiani Planum, eventually reaching the rim of the vast Endeavour Crater and finding clay minerals that pointed to ancient, less acidic water." },
      { stage: "Final signal", text: "A planet-wide dust storm blanketed the rover's solar panels in June 2018. Its last signal reached Earth on June 10, 2018." }
    ],
    discoveries: [
      { title: "Hematite \u2018blueberries\u2019", text: "Small mineral spheres scattered across the landing site formed in liquid water, some of the first direct mineral evidence of a wet Martian past." },
      { title: "Clay minerals at Endeavour Crater", text: "Later in its mission, Opportunity found clays that form only in water that is closer to neutral pH \u2014 potentially more hospitable to life than the acidic water suggested by earlier finds." },
      { title: "A record-setting traverse", text: "Opportunity's 45-kilometer journey let scientists study rock layers across a wide swath of Martian terrain, rather than a single site." }
    ],
    whyStopped: "In June 2018, a dust storm that eventually covered the entire planet blotted out sunlight over Opportunity's location. Unlike Spirit and Curiosity, Opportunity relied entirely on solar power with no heaters running off a nuclear source. Its batteries drained in the cold and dark, and engineers believe the rover likely suffered damage from the extreme low temperatures. After more than a thousand recovery commands over eight months, NASA declared the mission over on February 13, 2019.",
    whereNow: "Opportunity remains on the western rim of Perseverance Valley, inside Endeavour Crater, where it made its last transmission.",
    whatRemainsItems: ["Rover body and six wheels", "Cameras and science instruments", "Dust-covered solar panels and robotic arm"],
    whatRemains: "The rover sits silent on the crater rim, its solar panels still coated in the dust that ended its mission. Its scientific record \u2014 more than 217,000 images and 15 years of measurements \u2014 remains one of the most complete datasets ever gathered on another planet.",
    remainsCaption: "Opportunity's last signal faded, but the rover and its discoveries remain on Mars.",
    whyMatters: "It was supposed to last 90 days. It kept driving for 15 years, and every mile taught us something new about Mars.",
    quote: "I was told to drive a kilometer. I drove a marathon instead, and I'm still parked exactly where the dust finally caught up with me.",
    sources: [{ label: "NASA Science \u2014 Opportunity mission overview", url: "https://science.nasa.gov/mission/mer-opportunity/" }, { label: "NASA/JPL \u2014 Mars Exploration Rovers", url: "https://mars.nasa.gov/mer/" }]
  },
  {
    id: "sojourner",
    name: "Sojourner",
    subtitle: "Mars Pathfinder Rover",
    location: "mars",
    locationLabel: "Mars \u2014 Ares Vallis, Chryse Planitia",
    era: "1990s",
    status: "silent",
    statusLabel: "Silent",
    type: "Rover",
    launch: "December 4, 1996",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "July 4, 1997",
    plannedDuration: "7 sols, extendable to 30",
    actualDuration: "83 sols (about 85 Earth days) of active exploration",
    powerSource: "Solar array and onboard batteries",
    distance: "Roughly 100 meters (330 ft) driven",
    lastComm: "September 27, 1997 (last full data session)",
    missionEnd: "September 27, 1997 \u2014 Pathfinder's final data transmission",
    shortStory: "The first wheeled vehicle ever to explore another planet, Sojourner was a technology test that became a scientific success.",
    builtFor: "Sojourner rode to Mars aboard the Pathfinder lander to prove that a small, low-cost rover could operate on another world at all. It carried an instrument to measure the chemistry of nearby rocks and cameras to study the terrain immediately around the lander, then nicknamed the Carl Sagan Memorial Station.",
    journey: [
      { stage: "Launch", text: "Sojourner launched aboard Mars Pathfinder on December 4, 1996." },
      { stage: "Cruise", text: "The spacecraft traveled about seven months to reach Mars." },
      { stage: "Landing", text: "On July 4, 1997, Pathfinder bounced to a stop in Ares Vallis, and Sojourner rolled off its ramp the next day \u2014 the first wheels ever to touch another planet." },
      { stage: "First discoveries", text: "Sojourner examined nearby rocks, including one nicknamed 'Barnacle Bill,' finding chemistry consistent with rocks shaped by ancient water and volcanic activity." },
      { stage: "Extended mission", text: "Planned for a week, Sojourner kept working for 83 sols, far outliving its short warranty and proving that small rovers could survive the Martian environment." },
      { stage: "Final signal", text: "The lander's batteries failed as Martian winter set in, cutting Sojourner's only link to Earth. The last full data session was received on September 27, 1997." }
    ],
    discoveries: [
      { title: "Chemistry of Martian rocks", text: "Sojourner's alpha proton X-ray spectrometer measured the composition of rocks and soil, finding chemistry more like andesite (a volcanic rock) than expected." },
      { title: "Proof a rover could work at all", text: "Beyond specific findings, Sojourner demonstrated that a small, solar-powered rover could survive Martian temperature swings and dust, paving the way for every rover that followed." }
    ],
    whyStopped: "Sojourner itself never failed \u2014 it was still healthy when contact was lost. Its connection to Earth depended entirely on the stationary Pathfinder lander, which acted as a radio relay. As Martian winter approached, the lander's batteries degraded and it stopped communicating. Without the lander, Sojourner had no way to reach Earth. Engineers tried to restore contact for five months before formally ending the mission on March 10, 1998.",
    whereNow: "Sojourner remains parked near the Pathfinder lander in Ares Vallis, on the floodplain of an ancient Martian outflow channel.",
    whatRemainsItems: ["Sojourner rover and Pathfinder lander", "Rover cameras and APXS instrument", "Airbag landing system and lander instruments"],
    whatRemains: "Sojourner and the Pathfinder station still sit in Ares Vallis. The mission's real legacy is architectural: its airbag landing system and rover design became the direct ancestors of Spirit, Opportunity, Curiosity, and Perseverance.",
    remainsCaption: "Sojourner's short mission ended, but its little rover and Pathfinder lander remain together on Mars.",
    whyMatters: "It was the size of a microwave oven, built for a week-long test. It became the ancestor of every Mars rover that came after it.",
    quote: "I was the first set of wheels on another world. I only had a week to prove myself \u2014 I stretched that into 83 sols.",
    sources: [{ label: "NASA Science \u2014 Mars Pathfinder & Sojourner", url: "https://science.nasa.gov/mission/mars-pathfinder/" }, { label: "NASA/JPL \u2014 Mars Pathfinder mission", url: "https://mars.nasa.gov/mars-pathfinder/" }]
  },
  {
    id: "phoenix",
    name: "Phoenix",
    subtitle: "Mars Scout Lander",
    location: "mars",
    locationLabel: "Mars \u2014 Green Valley, Vastitas Borealis (north polar region)",
    era: "2000s",
    status: "silent",
    statusLabel: "Silent",
    type: "Stationary lander",
    launch: "August 4, 2007",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "May 25, 2008",
    plannedDuration: "90 sols",
    actualDuration: "157 sols (about 161 Earth days)",
    powerSource: "Solar panels charging rechargeable batteries",
    distance: "Stationary lander \u2014 did not rove",
    lastComm: "November 2, 2008",
    missionEnd: "Declared complete May 2010, after two winters with no response",
    shortStory: "Phoenix dug into Martian ice at the north pole, then went quiet as the polar winter buried it in darkness and frost.",
    builtFor: "Phoenix landed near the Martian arctic to study ice-rich soil directly, using a robotic arm to dig trenches and deliver samples to onboard ovens and chemistry labs. Its goal was to learn whether the icy ground could ever have supported microbial life.",
    journey: [
      { stage: "Launch", text: "Phoenix launched from Cape Canaveral on August 4, 2007." },
      { stage: "Cruise", text: "The spacecraft traveled roughly ten months to reach Mars." },
      { stage: "Landing", text: "On May 25, 2008, Phoenix touched down softly using retro-rockets rather than airbags, landing in the northern plain called Vastitas Borealis." },
      { stage: "First discoveries", text: "Within weeks, Phoenix's robotic arm confirmed water ice just beneath the surface, and cameras even recorded snow falling from Martian clouds." },
      { stage: "Extended mission", text: "Phoenix outlasted its 90-sol plan by two months, continuing to sample soil and monitor weather at the pole." },
      { stage: "Final signal", text: "As the Martian arctic winter approached, sunlight faded and temperatures dropped. Phoenix sent its last signal on November 2, 2008." }
    ],
    discoveries: [
      { title: "Confirmed water ice", text: "Phoenix's robotic arm exposed bright material beneath the surface that vaporized over a few days \u2014 confirmed to be water ice." },
      { title: "Perchlorate salts", text: "Chemistry experiments detected perchlorates in the soil, a finding with implications for both possible microbial life and future human exploration." },
      { title: "Snowfall observed", text: "A laser instrument detected snow falling from Martian clouds, the first time this had been directly observed on another planet." }
    ],
    whyStopped: "Phoenix landed too far north to survive the polar winter. As designed, its solar panels lost sunlight as the pole tilted away from the sun, and plunging temperatures were expected to damage its systems permanently. The lander's last transmission came on November 2, 2008; NASA listened for a signal through two more winters before declaring the mission complete in 2010.",
    whereNow: "Phoenix remains at its landing site in Vastitas Borealis, near the Martian north pole, now buried and reshaped by seasonal frost each winter.",
    whatRemainsItems: ["Lander frame and robotic arm", "Solar panels and science instruments", "Footpads beneath seasonal frost and carbon-dioxide ice"],
    whatRemains: "Orbital images later showed the lander's structure had been damaged by the weight of accumulated carbon-dioxide ice, exactly as engineers had expected. Its scientific results, though, reshaped how scientists think about water and habitability at the Martian poles.",
    remainsCaption: "Phoenix went quiet as winter closed in; its lander remains beneath the Martian polar seasons.",
    whyMatters: "It only had one Martian summer to work with \u2014 and it used it to confirm there is water ice, right under the surface, at the top of Mars.",
    quote: "I only had one Martian summer. I spent it digging into the ice I was sent to find, and I found it.",
    sources: [{ label: "NASA Science \u2014 Phoenix Mars Lander", url: "https://science.nasa.gov/mission/phoenix/" }, { label: "NASA/JPL \u2014 Phoenix mission", url: "https://mars.nasa.gov/phoenix/" }]
  },
  {
    id: "insight",
    name: "InSight",
    subtitle: "Interior Exploration using Seismic Investigations, Geodesy and Heat Transport",
    location: "mars",
    locationLabel: "Mars \u2014 Elysium Planitia",
    era: "2010s",
    status: "silent",
    statusLabel: "Silent",
    type: "Stationary lander",
    launch: "May 5, 2018",
    launchSite: "Vandenberg Space Force Base, California",
    arrivalLabel: "Landing",
    arrival: "November 26, 2018",
    plannedDuration: "About 2 Earth years (roughly 1 Martian year)",
    actualDuration: "Just over 4 years on the surface",
    powerSource: "Solar arrays charging rechargeable batteries",
    distance: "Stationary lander \u2014 did not rove",
    lastComm: "December 15, 2022",
    missionEnd: "December 21, 2022 \u2014 NASA formally ended the mission; last contact was December 15",
    shortStory: "InSight never moved an inch, but it let scientists listen to the inside of another planet for the first time.",
    builtFor: "InSight was built to study what lies beneath the Martian surface, not what's on top of it. A sensitive seismometer listened for marsquakes, while a heat probe was meant to measure warmth flowing from the planet's interior, together mapping Mars' crust, mantle, and core.",
    journey: [
      { stage: "Launch", text: "InSight launched on May 5, 2018 \u2014 the first interplanetary mission ever to launch from the U.S. West Coast." },
      { stage: "Cruise", text: "The spacecraft traveled about six months to reach Mars." },
      { stage: "Landing", text: "InSight landed on Elysium Planitia, a flat plain chosen specifically because it was geologically calm and safe, on November 26, 2018." },
      { stage: "First discoveries", text: "InSight's seismometer detected its first confirmed marsquake in April 2019, the first seismic tremor ever recorded on another planet." },
      { stage: "Extended mission", text: "Dust steadily built up on InSight's solar panels. Engineers used the robotic arm to trickle sand across the panels, briefly clearing some dust with the wind of falling grains." },
      { stage: "Final signal", text: "With power too low to sustain its systems, InSight sent its last message on December 15, 2022." }
    ],
    discoveries: [
      { title: "Over 1,300 marsquakes", text: "InSight detected more than a thousand seismic events, including the largest marsquake ever recorded, revealing that Mars is seismically active." },
      { title: "Mapped Mars' interior", text: "By studying how seismic waves traveled through the planet, scientists measured the size and structure of Mars' crust, mantle, and molten core for the first time." },
      { title: "Meteorite impacts detected seismically", text: "InSight linked seismic signals to fresh meteorite impact craters spotted from orbit, opening a new way to study impacts on other worlds." }
    ],
    whyStopped: "InSight's engineers knew from the start that its flat solar panels would slowly accumulate Martian dust with no wind strong enough, or rain, to clean them. Power output declined for years despite creative efforts to shake dust loose. The lander stopped responding after its last contact on December 15, 2022; NASA formally ended the mission on December 21.",
    whereNow: "InSight remains on the flat plain of Elysium Planitia, where it landed, its solar panels now coated in dust.",
    whatRemainsItems: ["Lander body and robotic arm", "Seismometer and heat-flow probe", "Dust-covered solar arrays"],
    whatRemains: "The lander's frame and instruments sit silently on the surface. Its most enduring contribution is invisible: years of seismic data that gave scientists their first real picture of what Mars looks like on the inside.",
    remainsCaption: "InSight's panels gathered dust, but its seismic record still lets us hear Mars from Earth.",
    whyMatters: "It never took a single step. It still mapped what no rover ever could \u2014 the inside of another planet.",
    quote: "I never moved. I didn't need to \u2014 I was listening to the whole planet shake beneath me.",
    sources: [{ label: "NASA Science \u2014 InSight mission overview", url: "https://science.nasa.gov/mission/insight/" }, { label: "NASA/JPL \u2014 InSight mission", url: "https://mars.nasa.gov/insight/" }]
  },
  {
    id: "surveyor-1",
    name: "Surveyor 1",
    subtitle: "Lunar Soft-Lander",
    location: "moon",
    locationLabel: "Moon \u2014 Oceanus Procellarum",
    era: "1960s",
    status: "silent",
    statusLabel: "Silent",
    type: "Lander",
    launch: "May 30, 1966",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "June 2, 1966",
    plannedDuration: "About 90 days of primary operations",
    actualDuration: "42-day primary mission; contact continued until January 7, 1967",
    powerSource: "Solar cells charging rechargeable batteries",
    distance: "Stationary lander",
    lastComm: "January 7, 1967",
    missionEnd: "January 7, 1967 \u2014 final engineering contact",
    shortStory: "The first American spacecraft to land softly on another world, Surveyor 1 proved the Moon's surface could hold the weight of a future astronaut.",
    builtFor: "Before NASA could risk sending astronauts to the Moon, engineers needed to know whether the surface was solid ground or, as some feared, a deep bed of dust that would swallow a spacecraft. Surveyor 1 carried a television camera and crushable footpads specifically to answer that question ahead of Apollo.",
    journey: [
      { stage: "Launch", text: "Surveyor 1 launched from Cape Canaveral on May 30, 1966, atop an Atlas-Centaur rocket." },
      { stage: "Cruise", text: "The spacecraft took just under three days to reach the Moon on a direct trajectory." },
      { stage: "Landing", text: "On June 2, 1966, Surveyor 1 became the first American spacecraft to soft-land on the Moon, touching down in Oceanus Procellarum." },
      { stage: "First discoveries", text: "Its footpads sank only a few centimeters into the lunar soil, proving the surface was firm enough to support a crewed lander." },
      { stage: "Extended mission", text: "Surveyor 1 survived its first lunar night \u2014 a two-week deep freeze \u2014 and returned to operation, sending back more than 11,000 images." },
      { stage: "Final signal", text: "Engineers maintained sporadic contact through several more lunar nights before the last signal was received on January 7, 1967." }
    ],
    discoveries: [
      { title: "The Moon could bear weight", text: "Surveyor 1's footpads confirmed the lunar surface was firm regolith, not deep dust, directly clearing a key uncertainty ahead of crewed Apollo landings." },
      { title: "First close-up lunar imagery", text: "Its television camera returned the first detailed, ground-level photographs of the lunar surface, including the first color images from the Moon." }
    ],
    whyStopped: "Surveyor 1 was never designed to survive indefinitely. It had already far outlived its planned lifetime, surviving several bitterly cold lunar nights that its systems were never guaranteed to withstand. After its last transmission on January 7, 1967, engineers judged the mission complete; its scientific job \u2014 proving a soft landing on the Moon was possible \u2014 had already succeeded.",
    whereNow: "Surveyor 1 remains exactly where it landed, in the Flamsteed P crater area of Oceanus Procellarum, on the Moon's near side.",
    whatRemainsItems: ["Lander frame and three landing legs", "Television camera", "Solar cells and engineering sensors"],
    whatRemains: "The lander still sits on the lunar surface today, undisturbed since 1967. It paved the way, literally, for every Surveyor and Apollo landing that followed.",
    remainsCaption: "Surveyor 1 proved a soft landing was possible; its lander remains where it first touched down.",
    whyMatters: "It was a single lander sent to answer one question: can we land here? The answer it sent back made the Moon landings possible.",
    quote: "I only had to prove the ground beneath me was solid. I'm still standing on it.",
    sources: [{ label: "NASA Science \u2014 Surveyor 1 mission", url: "https://science.nasa.gov/mission/surveyor-1/" }, { label: "NASA History \u2014 Surveyor program", url: "https://history.nasa.gov/SP-4210/pages/TOC.htm" }]
  },
  {
    id: "surveyor-3",
    name: "Surveyor 3",
    subtitle: "Lunar Soft-Lander",
    location: "moon",
    locationLabel: "Moon \u2014 Oceanus Procellarum",
    era: "1960s",
    status: "silent",
    statusLabel: "Silent",
    type: "Lander",
    launch: "April 17, 1967",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "April 20, 1967",
    plannedDuration: "About 90 days",
    actualDuration: "About 14 days of surface operations",
    powerSource: "Solar cells charging rechargeable batteries",
    distance: "Stationary lander",
    lastComm: "May 4, 1967",
    missionEnd: "May 4, 1967 \u2014 last contact, two days into lunar night",
    shortStory: "Surveyor 3 dug into the Moon with the first robotic scoop \u2014 and became the only spacecraft astronauts have ever revisited on another world.",
    builtFor: "Surveyor 3 carried a robotic scoop, the first ever sent to another planetary body, to test how lunar soil behaved when dug into and to help engineers understand its load-bearing strength for future Apollo landers.",
    journey: [
      { stage: "Launch", text: "Surveyor 3 launched on April 17, 1967." },
      { stage: "Cruise", text: "It reached the Moon in about three days." },
      { stage: "Landing", text: "Surveyor 3 landed on April 20, 1967, bouncing several times inside a small crater in Oceanus Procellarum before settling on a slope." },
      { stage: "First discoveries", text: "Its scoop dug several trenches, giving engineers their first direct measurements of lunar soil mechanics." },
      { stage: "Later visit", text: "Apollo 12 landed nearby on November 19, 1969. On November 20, Pete Conrad and Alan Bean walked to Surveyor 3, examined it, and removed parts to return to Earth." },
      { stage: "Final signal", text: "Surveyor 3's mission ended after about two weeks. Its final contact was May 4, 1967, more than two years before Apollo 12 arrived." }
    ],
    discoveries: [
      { title: "First robotic digging on another world", text: "Surveyor 3's scoop tested how lunar soil resisted digging, informing the design of Apollo's lunar module landing legs and astronaut tools." },
      { title: "A spacecraft studied by astronauts", text: "Parts removed by Apollo 12 astronauts \u2014 including its camera \u2014 let scientists study how over two years of space exposure had affected the hardware." }
    ],
    whyStopped: "Surveyor 3's mission ended naturally after about two weeks when engineers had gathered the engineering data they needed. Its last contact was May 4, 1967, two days after lunar night began. It was already silent when Apollo 12 visited more than two years later.",
    whereNow: "Surveyor 3 still sits inside its small unnamed crater in Oceanus Procellarum, about 180 meters from the Apollo 12 landing site.",
    whatRemainsItems: ["Lander frame, legs, and solar cells", "Most instruments and landing radar", "Camera system and soil scoop were returned to Earth by Apollo 12"],
    whatRemains: "Most of the lander remains on the Moon, missing the camera system and soil scoop recovered by Apollo 12. It is the only spacecraft on another world that astronauts have visited in person.",
    remainsCaption: "Surveyor 3 fell silent, then Apollo 12 astronauts returned to inspect it and bring pieces home.",
    whyMatters: "It dug the first trench on another world. Two years later, two astronauts walked over to shake its hand.",
    quote: "I dug the first trench anyone ever dug on another world. Years later, two astronauts walked over just to see how I'd held up.",
    sources: [{ label: "NASA Science \u2014 Surveyor 3 mission", url: "https://science.nasa.gov/mission/surveyor-3/" }, { label: "NASA Apollo 12 Lunar Surface Journal", url: "https://history.nasa.gov/alsj/a12/a12.html" }]
  },
  {
    id: "surveyor-5",
    name: "Surveyor 5",
    subtitle: "Lunar Soft-Lander",
    location: "moon",
    locationLabel: "Moon \u2014 Mare Tranquillitatis",
    era: "1960s",
    status: "silent",
    statusLabel: "Silent",
    type: "Lander",
    launch: "September 8, 1967",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "September 11, 1967 UTC (September 10 local date in Florida)",
    plannedDuration: "About 90 days",
    actualDuration: "About 3 months of intermittent operation",
    powerSource: "Solar cells charging rechargeable batteries",
    distance: "Stationary lander",
    lastComm: "December 16, 1967",
    missionEnd: "December 16, 1967 \u2014 contact lost",
    shortStory: "Surveyor 5 landed almost exactly where Apollo 11 would touch down two years later \u2014 and carried the first instrument to test lunar soil chemistry.",
    builtFor: "Surveyor 5 carried an alpha-scattering instrument, the first sent to another world, designed to measure the chemical composition of lunar soil directly on the surface.",
    journey: [
      { stage: "Launch", text: "Surveyor 5 launched on September 8, 1967, after a last-minute fuel-leak scare on the launch pad." },
      { stage: "Cruise", text: "It reached the Moon in just under three days." },
      { stage: "Landing", text: "Surveyor 5 landed on September 11, 1967 UTC (September 10 in Florida), in Mare Tranquillitatis, about 25 kilometers from the Apollo 11 site." },
      { stage: "First discoveries", text: "Its alpha-scattering instrument returned the first chemical analysis of lunar soil, finding it similar to basaltic rock on Earth." },
      { stage: "Extended mission", text: "Surveyor 5 survived one lunar night and resumed limited operations into a second lunar day." },
      { stage: "Final signal", text: "Contact was lost as its second lunar night approached; NASA records the last contact as December 16, 1967 UTC." }
    ],
    discoveries: [
      { title: "First soil chemistry from another world", text: "Surveyor 5's alpha-scattering instrument showed lunar soil at the site was chemically similar to terrestrial basalt, directly informing what Apollo 11's crew could expect to find." },
      { title: "Reconnaissance for Apollo 11", text: "Its landing site sat close enough to the future Apollo 11 site that its data helped confirm the area's suitability for a crewed landing." }
    ],
    whyStopped: "Surveyor 5 had already completed its planned mission and survived longer than expected, including one lunar night. As a second lunar night approached, contact was lost on December 16, 1967 UTC, and the mission was considered complete.",
    whereNow: "Surveyor 5 remains in Mare Tranquillitatis, about 25 kilometers from the Apollo 11 landing site.",
    whatRemainsItems: ["Lander frame and three legs", "Television camera and alpha-scattering instrument", "Solar cells and footpad magnet"],
    whatRemains: "The lander is still there today. Its soil analysis helped clear the way for humans to walk nearby for the first time.",
    remainsCaption: "Surveyor 5's soil analysis helped prepare for Apollo; the lander remains near Tranquility Base.",
    whyMatters: "It tested the chemistry of the ground two years before Apollo 11 walked on it.",
    quote: "I tasted the soil at Tranquility Base before anyone ever set foot there.",
    sources: [{ label: "NASA Science \u2014 Surveyor 5 mission", url: "https://science.nasa.gov/mission/surveyor-5/" }, { label: "NASA History \u2014 Surveyor program", url: "https://history.nasa.gov/SP-4210/pages/TOC.htm" }]
  },
  {
    id: "surveyor-6",
    name: "Surveyor 6",
    subtitle: "Lunar Soft-Lander",
    location: "moon",
    locationLabel: "Moon \u2014 Sinus Medii",
    era: "1960s",
    status: "silent",
    statusLabel: "Silent",
    type: "Lander",
    launch: "November 7, 1967",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "November 10, 1967",
    plannedDuration: "About 90 days",
    actualDuration: "Less than two weeks of primary operations; brief contact resumed December 14",
    powerSource: "Solar cells charging rechargeable batteries",
    distance: "Hopped about 2.5 meters (8 ft) across the surface",
    lastComm: "December 14, 1967",
    missionEnd: "December 14, 1967",
    shortStory: "Surveyor 6 did something no spacecraft had done before: it fired its engines and hopped, becoming the first vehicle to lift off from another world.",
    builtFor: "Surveyor 6 landed near the Moon's center-facing hemisphere to continue testing soil composition and surface conditions in a region being considered for future Apollo landings.",
    journey: [
      { stage: "Launch", text: "Surveyor 6 launched on November 7, 1967." },
      { stage: "Cruise", text: "It reached the Moon in about three days." },
      { stage: "Landing", text: "Surveyor 6 landed on November 10, 1967, in Sinus Medii, close to the Moon's near-side center." },
      { stage: "First discoveries", text: "Its alpha-scattering instrument gathered more lunar soil chemistry data, reinforcing findings from Surveyor 5." },
      { stage: "A historic hop", text: "On November 17, 1967, Surveyor 6 fired its thrusters for 2.5 seconds, rising about 3 meters and landing 2.5 meters west \u2014 the first liftoff from another celestial body." },
      { stage: "Final signal", text: "Surveyor 6 continued operating until its last transmission on December 14, 1967." }
    ],
    discoveries: [
      { title: "First liftoff from another world", text: "Surveyor 6's brief engine firing and re-landing demonstrated that a spacecraft could lift off and land again on another celestial body, a capability essential to every crewed Moon landing that followed." },
      { title: "More soil chemistry data", text: "Its measurements added to Surveyor 5's findings, building a broader chemical picture of the lunar near side." }
    ],
    whyStopped: "Surveyor 6 completed its planned experiments, including its historic hop, well within its expected lifetime. Its last transmission came on December 14, 1967, as its mission goals had already been met and lunar night approached.",
    whereNow: "Surveyor 6 remains in Sinus Medii, about 2.5 meters west of its original landing spot after its 1967 hop.",
    whatRemainsItems: ["Lander frame and three legs", "Television camera and science instruments", "Solar cells and relocated landing site"],
    whatRemains: "The lander sits undisturbed on the lunar surface. Its short hop remains one of the lesser-known but foundational proofs behind every crewed lunar liftoff since.",
    remainsCaption: "Surveyor 6 hopped, landed again, and remains a few meters from its original touchdown point.",
    whyMatters: "For 2.5 seconds, it became the first spacecraft to ever launch from another world \u2014 and land again, just a few feet away.",
    quote: "For two and a half seconds, I flew. Nobody had ever done that on another world before.",
    sources: [{ label: "NASA Science \u2014 Surveyor 6 mission", url: "https://science.nasa.gov/mission/surveyor-6/" }, { label: "NASA History \u2014 Surveyor program", url: "https://history.nasa.gov/SP-4210/pages/TOC.htm" }]
  },
  {
    id: "surveyor-7",
    name: "Surveyor 7",
    subtitle: "Lunar Soft-Lander",
    location: "moon",
    locationLabel: "Moon \u2014 near Tycho Crater",
    era: "1960s",
    status: "silent",
    statusLabel: "Silent",
    type: "Lander",
    launch: "January 7, 1968",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Landing",
    arrival: "January 10, 1968",
    plannedDuration: "About 90 days",
    actualDuration: "About 6 weeks of operation",
    powerSource: "Solar cells charging rechargeable batteries",
    distance: "Stationary lander",
    lastComm: "February 21, 1968",
    missionEnd: "February 21, 1968",
    shortStory: "The last of the Surveyor landers, Surveyor 7 skipped the flat mare plains for the rugged highlands, purely for science instead of Apollo planning.",
    builtFor: "Unlike its predecessors, Surveyor 7 was not sent to a candidate Apollo landing site. By 1968 NASA had enough data from earlier landers, so Surveyor 7 targeted the scientifically rich highlands near Tycho Crater to study terrain more representative of the Moon as a whole.",
    journey: [
      { stage: "Launch", text: "Surveyor 7 launched on January 7, 1968, the last mission of the program." },
      { stage: "Cruise", text: "It reached the Moon in about three days." },
      { stage: "Landing", text: "Surveyor 7 landed on January 10, 1968, on the rim of Tycho Crater, one of the Moon's most prominent and rugged features." },
      { stage: "First discoveries", text: "Its cameras and alpha-scattering instrument found highland soil chemically different from the mare sites explored by earlier Surveyors." },
      { stage: "Extended mission", text: "Surveyor 7 also used a magnet on its scoop to test for magnetic material in lunar soil and photographed the surrounding highland terrain in detail." },
      { stage: "Final signal", text: "It sent its last transmission on February 21, 1968, concluding both its own mission and the Surveyor program." }
    ],
    discoveries: [
      { title: "Highland soil composition", text: "Surveyor 7 found the highland soil near Tycho was chemically different from the darker mare soils sampled by earlier landers, showing the Moon's surface was more varied than expected." },
      { title: "A close-up view of Tycho Crater", text: "Its images gave scientists their first ground-level look at the rugged terrain of a major lunar highland crater." }
    ],
    whyStopped: "Surveyor 7 had no crewed mission riding on its results, so once it completed its planned science \u2014 including imaging the surrounding highlands and testing soil chemistry \u2014 its mission concluded on schedule. Its last signal was received on February 21, 1968, ending the five-lander Surveyor program on a purely scientific note.",
    whereNow: "Surveyor 7 remains on Tycho crater's ejecta blanket, about 29 kilometers north of the crater rim.",
    whatRemainsItems: ["Lander frame and three legs", "Television camera, scoop, and alpha-scattering instrument", "Solar cells and footpad magnets"],
    whatRemains: "The lander is still there, in one of the more dramatic landscapes any spacecraft has explored. It closed out a program that made every subsequent Moon landing possible.",
    remainsCaption: "Surveyor 7 completed the program's final science mission; its lander remains in the lunar highlands.",
    whyMatters: "It didn't need to scout a landing site for astronauts. By the time it launched, it could just go do the science.",
    quote: "The others scouted the flat ground for astronauts. I got to go look at the mountains.",
    sources: [{ label: "NASA Science \u2014 Surveyor 7 mission", url: "https://science.nasa.gov/mission/surveyor-7/" }, { label: "NASA History \u2014 Surveyor program", url: "https://history.nasa.gov/SP-4210/pages/TOC.htm" }]
  },
  {
    id: "apollo-lm",
    name: "Apollo Lunar Modules",
    subtitle: "Descent Stages, Apollo 11\u201317",
    location: "moon",
    locationLabel: "Moon \u2014 six landing sites across the near side",
    era: "1970s",
    status: "no-longer-operational",
    statusLabel: "No Longer Operational",
    type: "Crewed lander hardware",
    launch: "1969\u20131972 (six missions)",
    launchSite: "Kennedy Space Center, Florida",
    arrivalLabel: "Landings",
    arrival: "Six landings between July 1969 and December 1972",
    plannedDuration: "Hours to just over 3 days on the surface per mission",
    actualDuration: "Descent stages remain permanently on the Moon",
    powerSource: "Silver-zinc batteries powered the Lunar Module; descent-stage hardware was left behind by design",
    distance: "Varies by mission \u2014 astronauts explored on foot and by lunar rover",
    lastComm: "N/A \u2014 hardware is inert, not a communications mission",
    missionEnd: "Each descent stage was left behind at liftoff as a launch platform for the ascent stage",
    shortStory: "Six lunar modules carried astronauts to the Moon. Each time, half of the spacecraft stayed behind \u2014 permanently.",
    builtFor: "The Apollo Lunar Module was a two-part spacecraft: a descent stage that carried astronauts down to the surface, and an ascent stage that carried them back up to lunar orbit. The descent stage doubled as a launch pad for the ascent stage, so by design it could never come home.",
    journey: [
      { stage: "Launch", text: "Between 1969 and 1972, six Apollo missions \u2014 11, 12, 14, 15, 16, and 17 \u2014 launched from Kennedy Space Center carrying a Lunar Module to the Moon." },
      { stage: "Descent", text: "On each mission, the descent stage's engine lowered the spacecraft to the surface, its four landing legs absorbing the touchdown." },
      { stage: "Surface operations", text: "Astronauts lived and worked out of the Lunar Module for periods ranging from about a day (Apollo 11) to more than three days (Apollo 15\u201317), using its descent stage as a base, a workbench, and, on later missions, a garage for the Lunar Roving Vehicle." },
      { stage: "Liftoff", text: "When it was time to leave, the ascent stage's engine fired, using the descent stage as a stationary launch platform, exactly as designed." },
      { stage: "Left behind", text: "The descent stage, its job complete, stayed on the Moon permanently at each of the six landing sites." }
    ],
    discoveries: [
      { title: "842 pounds of lunar samples", text: "Astronauts using the Lunar Modules as their base of operations collected rock and soil samples that are still studied today, reshaping scientific understanding of the Moon's formation and history." },
      { title: "Seismometers and long-term experiments", text: "Several missions left instrument packages near the descent stages, including seismometers that recorded moonquakes for years after the astronauts departed." },
      { title: "Proof crewed planetary landings were possible", text: "Beyond any single measurement, six successful landings and returns proved that humans could safely travel to another world, work there, and come home." }
    ],
    whyStopped: "The descent stages were never meant to return. By design, each one served as a launch platform: its structure and legs stayed on the surface while the ascent stage above it fired its engine and lifted the astronauts back into lunar orbit to rejoin the command module. Leaving the descent stage behind wasn't a failure \u2014 it was the plan from the very first blueprint.",
    whereNow: "Six descent stages remain at their respective landing sites: Tranquility Base (Apollo 11), Ocean of Storms (Apollo 12), Fra Mauro (Apollo 14), Hadley\u2013Apennine (Apollo 15), Descartes Highlands (Apollo 16), and Taurus\u2013Littrow (Apollo 17).",
    whatRemainsItems: ["Six Lunar Module descent stages and landing legs", "Apollo experiment packages and discarded equipment", "Lunar Roving Vehicles at Apollo 15, 16, and 17 sites"],
    whatRemains: "Each descent stage still stands at its landing site, along with experiment packages, discarded equipment, and in three cases, the Lunar Roving Vehicle. Modern lunar orbiters have photographed several of these sites from above, showing the hardware and astronaut footpaths still visible in the undisturbed lunar dust.",
    remainsCaption: "The ascent stages carried the crews home; six descent stages and their surface traces remain on the Moon.",
    whyMatters: "They were never meant to come home. They were meant to get someone else there \u2014 and they did, six times.",
    quote: "I was only ever half of the journey. I stayed on the surface so the rest of the spacecraft, and the crew, could go home.",
    sources: [{ label: "NASA \u2014 Apollo program and missions", url: "https://www.nasa.gov/the-apollo-program/" }, { label: "NASA Science \u2014 Lunar Reconnaissance Orbiter", url: "https://science.nasa.gov/mission/lunar-reconnaissance-orbiter/" }]
  },
  {
    id: "pioneer-10",
    name: "Pioneer 10",
    subtitle: "Outer Planets and Heliosphere Probe",
    location: "deepspace",
    locationLabel: "Deep Space \u2014 heading toward the star Aldebaran",
    era: "1970s",
    status: "silent",
    statusLabel: "Silent",
    type: "Flyby probe",
    launch: "March 2, 1972",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Jupiter flyby",
    arrival: "December 4, 1973 (UTC)",
    plannedDuration: "21 months, to reach and study Jupiter",
    actualDuration: "Nearly 31 years of operation",
    powerSource: "Two SNAP-19 radioisotope thermoelectric generators (RTGs)",
    distance: "Was roughly 80 AU (about 12 billion km) from Earth at last contact",
    lastComm: "January 23, 2003 (last signal); April 27, 2002 (last usable data)",
    missionEnd: "Routine mission ended March 31, 1997; final contact attempted through 2003",
    shortStory: "Pioneer 10 was the first spacecraft to fly past Jupiter, and the first to head permanently out of the solar system.",
    builtFor: "Pioneer 10 was designed to test whether a spacecraft could even survive a trip through the asteroid belt and past Jupiter's intense radiation, while also returning the first close-up images and data from the largest planet in the solar system.",
    journey: [
      { stage: "Launch", text: "Pioneer 10 launched on March 2, 1972, becoming the fastest human-made object to leave Earth up to that point." },
      { stage: "Asteroid belt", text: "It became the first spacecraft to successfully cross the main asteroid belt, proving the region wasn't as hazardous to spacecraft as some had feared." },
      { stage: "Jupiter flyby", text: "On December 4, 1973 UTC, Pioneer 10 passed about 130,000 km from Jupiter's cloud tops and returned the first close-up images of the planet." },
      { stage: "Outward journey", text: "After Jupiter, Pioneer 10 continued outward, crossing the orbits of Saturn, Uranus, Neptune, and eventually Pluto by 1983." },
      { stage: "Fading signal", text: "As its plutonium power source steadily decayed over three decades, Pioneer 10's signal grew fainter each year." },
      { stage: "Final signal", text: "Its last, very weak signal was received on January 23, 2003, at a distance of roughly 12 billion kilometers from Earth." }
    ],
    discoveries: [
      { title: "First close-up images of Jupiter", text: "Pioneer 10 returned humanity's first detailed photographs of Jupiter's cloud bands and Great Red Spot from close range." },
      { title: "Proved the asteroid belt was passable", text: "By successfully crossing the belt, Pioneer 10 showed later missions, including Voyager, that the region wasn't an impassable debris field." },
      { title: "Mapped Jupiter's radiation environment", text: "Instruments measured intense radiation around Jupiter, data engineers used to help protect later spacecraft, including Voyager and Galileo." }
    ],
    whyStopped: "Pioneer 10 ran on a radioisotope thermoelectric generator, which converts the heat of decaying plutonium into electricity. That heat source naturally weakens over time, and by the early 2000s the spacecraft simply didn't have enough power left to run its transmitter. Its last detectable signal arrived on January 23, 2003; a final attempt to contact it in 2006 heard nothing back.",
    whereNow: "Pioneer 10 is coasting silently through interstellar space in the direction of the constellation Taurus. It carries a gold plaque with a message about humanity and Earth's location, in case it is ever found.",
    whatRemainsItems: ["Pioneer 10 spacecraft and science instruments", "Two radioisotope generators", "Aluminum Pioneer plaque"],
    whatRemains: "The spacecraft itself is intact and still traveling, though it can no longer communicate. At its current speed, it would take Pioneer 10 roughly two million years to reach the star Aldebaran, though it isn't headed directly at it and will likely never arrive.",
    remainsCaption: "Pioneer 10 no longer transmits, but the spacecraft and its message continue outward.",
    whyMatters: "It was built for a 21-month trip to Jupiter. It's still traveling today, carrying a message from Earth into the space between the stars.",
    quote: "I was only supposed to survive Jupiter's radiation belts. I outlived that by three decades, and I'm still moving.",
    sources: [{ label: "NASA Science \u2014 Pioneer 10 mission history", url: "https://science.nasa.gov/mission/pioneer-10/" }, { label: "NASA \u2014 Pioneer 10 launch history", url: "https://www.nasa.gov/history/50-years-ago-pioneer-10-launches-to-explore-jupiter/" }]
  },
  {
    id: "pioneer-11",
    name: "Pioneer 11",
    subtitle: "Outer Planets and Heliosphere Probe",
    location: "deepspace",
    locationLabel: "Deep Space \u2014 heading toward the constellation Aquila",
    era: "1970s",
    status: "silent",
    statusLabel: "Silent",
    type: "Flyby probe",
    launch: "April 6, 1973",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Saturn flyby",
    arrival: "September 1, 1979",
    plannedDuration: "About 2 years, to reach Jupiter",
    actualDuration: "About 22.5 years of operation",
    powerSource: "Four SNAP-19 radioisotope thermoelectric generators (RTGs)",
    distance: "Was roughly 44 AU from Earth at last contact",
    lastComm: "September 30, 1995 (last contact); engineering data received November 24, 1995",
    missionEnd: "September 30, 1995",
    shortStory: "Pioneer 11 followed its twin past Jupiter, then became the first spacecraft to ever visit Saturn.",
    builtFor: "Pioneer 11 was built as a follow-up to Pioneer 10, using a gravity assist from Jupiter to reach Saturn, a planet no spacecraft had ever approached, to study its rings, moons, and radiation environment up close for the first time.",
    journey: [
      { stage: "Launch", text: "Pioneer 11 launched on April 6, 1973, a year after its twin." },
      { stage: "Jupiter flyby", text: "In 1974, Pioneer 11 passed even closer to Jupiter than Pioneer 10, using the planet's gravity to bend its path toward Saturn." },
      { stage: "Saturn flyby", text: "On September 1, 1979, Pioneer 11 became the first spacecraft to fly past Saturn, passing within about 21,000 km of its rings." },
      { stage: "Outward journey", text: "After Saturn, Pioneer 11 continued outward on a path that would eventually take it out of the solar system in the opposite direction from Pioneer 10." },
      { stage: "Fading signal", text: "As with its twin, Pioneer 11's plutonium power source gradually weakened over two decades of flight." },
      { stage: "Final signal", text: "Its last transmission was received on September 30, 1995, by which point Earth had moved out of view of its fixed antenna." }
    ],
    discoveries: [
      { title: "First-ever flyby of Saturn", text: "Pioneer 11 provided the first close-up data on Saturn's rings and atmosphere, and discovered two new moons and an additional ring." },
      { title: "Scouted a path for Voyager", text: "Its successful passage through Saturn's ring plane confirmed a safe route that the Voyager spacecraft would later use." },
      { title: "Extended radiation and magnetic field data", text: "Combined with Pioneer 10, its instruments built the first broad picture of the outer solar system's radiation and magnetic environment." }
    ],
    whyStopped: "Like Pioneer 10, Pioneer 11's power came from a decaying plutonium heat source that grew weaker every year. By 1995, the spacecraft's fixed antenna could no longer be pointed at Earth as our planet's motion carried it out of view, and the fading power supply made further contact impractical. Its last transmission was received on September 30, 1995.",
    whereNow: "Pioneer 11 is traveling silently toward the constellation Aquila, in roughly the opposite direction from Pioneer 10.",
    whatRemainsItems: ["Pioneer 11 spacecraft and science instruments", "Four radioisotope generators", "Aluminum Pioneer plaque"],
    whatRemains: "The spacecraft is intact and still moving through space, carrying the same metal plaque as its twin. It is expected to pass near Lambda Aquilae in about four million years.",
    remainsCaption: "Pioneer 11's radio went quiet, but its spacecraft and plaque continue into deep space.",
    whyMatters: "It was the first spacecraft to ever see Saturn up close \u2014 and it did it on a mission that started out just trying to reach Jupiter.",
    quote: "Nobody had ever flown past Saturn before me. I got there by borrowing a boost from Jupiter's gravity.",
    sources: [{ label: "NASA Science \u2014 Pioneer 11 mission history", url: "https://science.nasa.gov/mission/pioneer-11/" }, { label: "NASA Science \u2014 Pioneer spacecraft facts", url: "https://science.nasa.gov/missions/pioneer/pioneer-11/10-things-about-pioneer-spacecraft/" }]
  },
  {
    id: "voyager-1",
    name: "Voyager 1",
    subtitle: "Outer Planets and Interstellar Mission",
    location: "deepspace",
    locationLabel: "Interstellar space \u2014 the most distant human-made object",
    era: "1970s",
    status: "traveling",
    statusLabel: "Still Traveling",
    type: "Flyby probe",
    launch: "September 5, 1977",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Entered interstellar space",
    arrival: "August 25, 2012",
    plannedDuration: "About 5 years, for the Jupiter\u2013Saturn tour",
    actualDuration: "Operating for over 48 years and counting",
    powerSource: "Three radioisotope thermoelectric generators (RTGs)",
    distance: "More than 170 AU from the Sun; distance continues to increase",
    lastComm: "Still in intermittent contact with NASA's Deep Space Network",
    missionEnd: "Active mission \u2014 NASA continues power-management operations",
    shortStory: "Launched in 1977 on a five-year plan, Voyager 1 is still transmitting from interstellar space nearly five decades later.",
    builtFor: "Voyager 1 was built to take advantage of a rare alignment of the outer planets, flying past Jupiter and Saturn to study them and their moons up close, before its trajectory sent it permanently out of the solar system.",
    journey: [
      { stage: "Launch", text: "Voyager 1 launched on September 5, 1977, sixteen days after its twin, Voyager 2, but on a faster path." },
      { stage: "Jupiter flyby", text: "Voyager 1 flew past Jupiter in 1979, discovering active volcanoes on the moon Io \u2014 the first seen anywhere beyond Earth." },
      { stage: "Saturn flyby", text: "In 1980, Voyager 1 flew past Saturn and its moon Titan, sending its trajectory up and out of the plane of the planets." },
      { stage: "Outward journey", text: "With its planetary flybys complete, Voyager 1 continued outward for decades, eventually overtaking Pioneer 10 as the most distant human-made object in 1998." },
      { stage: "Interstellar space", text: "On August 25, 2012, Voyager 1 became the first spacecraft to cross into interstellar space, beyond the Sun's protective bubble of solar wind." },
      { stage: "Still transmitting", text: "Voyager 1 continues to send back data today, though NASA has powered down several instruments to conserve its dwindling energy supply." }
    ],
    discoveries: [
      { title: "Active volcanoes on Io", text: "Voyager 1 found erupting volcanoes on Jupiter's moon Io, the first active volcanism ever observed outside Earth." },
      { title: "Crossed into interstellar space", text: "In 2012, Voyager 1 became the first human-made object confirmed to leave the heliosphere, the bubble of charged particles blown out by the Sun." },
      { title: "The Pale Blue Dot", text: "In 1990, on its way out of the solar system, Voyager 1 turned its camera back and photographed Earth from about 6 billion kilometers away." }
    ],
    whyStopped: "It has not stopped. Voyager 1 is still transmitting, though its radioisotope power source gradually weakens. NASA continues to power down selected systems and instruments to preserve the spacecraft's remaining science capability.",
    whereNow: "Voyager 1 is more than 170 astronomical units from the Sun and moving farther away, making it the most distant human-made object in existence.",
    whatRemainsItems: ["Voyager 1 spacecraft and its operating instruments", "Three RTGs with diminishing electrical output", "The Golden Record and its cover"],
    whatRemains: "The spacecraft is still active today, sending data from a region of space no other human-made object has ever reached. It carries the Golden Record, a collection of sounds and images meant to represent life on Earth to anyone, or anything, that might one day find it.",
    remainsCaption: "Voyager 1 is still transmitting from interstellar space; when its instruments fall silent, the spacecraft will keep traveling.",
    whyMatters: "It's still out there, still talking to us, from farther away than any human-made object has ever traveled.",
    quote: "I was only supposed to tour Jupiter and Saturn. Instead I kept going, and I still haven't stopped.",
    sources: [{ label: "NASA Science \u2014 Voyager mission updates", url: "https://science.nasa.gov/mission/voyager/" }, { label: "NASA/JPL \u2014 Voyager mission status", url: "https://voyager.jpl.nasa.gov/mission/status/" }]
  },
  {
    id: "voyager-2",
    name: "Voyager 2",
    subtitle: "Outer Planets and Interstellar Mission",
    location: "deepspace",
    locationLabel: "Interstellar space \u2014 the only probe to visit all four giant planets",
    era: "1970s",
    status: "traveling",
    statusLabel: "Still Traveling",
    type: "Flyby probe",
    launch: "August 20, 1977",
    launchSite: "Cape Canaveral, Florida",
    arrivalLabel: "Entered interstellar space",
    arrival: "November 5, 2018",
    plannedDuration: "About 5 years, for the Jupiter\u2013Saturn tour",
    actualDuration: "Operating for over 48 years and counting",
    powerSource: "Three radioisotope thermoelectric generators (RTGs)",
    distance: "More than 140 AU from the Sun; distance continues to increase",
    lastComm: "Still in intermittent contact with NASA's Deep Space Network",
    missionEnd: "Active mission \u2014 NASA continues power-management operations",
    shortStory: "Voyager 2 is the only spacecraft ever to fly past Uranus and Neptune, and it's still sending data home from beyond the Sun's reach.",
    builtFor: "Voyager 2 launched on a trajectory designed to take advantage of a once-every-176-years alignment of the outer planets, allowing it to visit all four giant planets in a single mission using gravity assists from each one.",
    journey: [
      { stage: "Launch", text: "Voyager 2 launched on August 20, 1977, ahead of Voyager 1, on a slower but more far-reaching trajectory." },
      { stage: "Jupiter and Saturn", text: "Voyager 2 flew past Jupiter in 1979 and Saturn in 1981, gathering data that complemented its twin's discoveries." },
      { stage: "Uranus flyby", text: "In 1986, Voyager 2 became the only spacecraft ever to fly past Uranus, discovering new moons and rings." },
      { stage: "Neptune flyby", text: "In 1989, Voyager 2 flew past Neptune, its last planetary encounter, discovering active geysers on the moon Triton." },
      { stage: "Interstellar space", text: "On November 5, 2018, Voyager 2 crossed into interstellar space, six years after Voyager 1, taking a different route out of the solar system." },
      { stage: "Still transmitting", text: "Voyager 2 continues to return data today, with several instruments powered down over the years to conserve energy." }
    ],
    discoveries: [
      { title: "Only visit ever to Uranus and Neptune", text: "Voyager 2 remains the only spacecraft to have ever flown past either Uranus or Neptune, discoveries that shaped decades of textbook knowledge about the outer planets." },
      { title: "Geysers on Triton", text: "At Neptune, Voyager 2 spotted active nitrogen geysers erupting from the surface of the moon Triton, evidence of ongoing geologic activity far from the Sun." },
      { title: "Confirmed the heliosphere's edge", text: "By crossing into interstellar space in 2018, Voyager 2 provided a second data point, alongside Voyager 1, for mapping the boundary of the Sun's influence." }
    ],
    whyStopped: "It has not stopped. Voyager 2's radioisotope power source gradually weakens, and NASA continues to manage its power and instrument use to extend the science mission.",
    whereNow: "Voyager 2 is more than 140 astronomical units from the Sun, traveling below the plane of the planets and still moving outward.",
    whatRemainsItems: ["Voyager 2 spacecraft and its operating instruments", "Three RTGs with diminishing electrical output", "The Golden Record and its cover"],
    whatRemains: "The spacecraft is still active, sending back measurements of interstellar space no other probe has gathered. Like its twin, it carries a Golden Record with sounds and images of Earth.",
    remainsCaption: "Voyager 2 still sends science from interstellar space; the craft and Golden Record will continue long after contact ends.",
    whyMatters: "It's the only spacecraft that has ever seen Uranus or Neptune up close, and it's still flying, decades after that job was done.",
    quote: "I'm still the only one who has ever seen Uranus or Neptune up close. I'm not done traveling yet.",
    sources: [{ label: "NASA Science \u2014 Voyager mission updates", url: "https://science.nasa.gov/mission/voyager/" }, { label: "NASA/JPL \u2014 Voyager mission status", url: "https://voyager.jpl.nasa.gov/mission/status/" }]
  }
];

const ERA_ORDER = ["1960s", "1970s", "1980s", "1990s", "2000s", "2010s", "2020s"];

const STATUS_LABELS = {
  silent: "Silent",
  "no-longer-operational": "No Longer Operational",
  traveling: "Still Traveling",
  completed: "Completed"
};

const LOCATION_LABELS = {
  mars: "Mars",
  moon: "Moon",
  deepspace: "Deep Space"
};

function getMissionById(id) {
  return MISSIONS.find(function (m) { return m.id === id; });
}
